# Generated by Django 3.0.3 on 2020-03-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('can_add_question', 'allows user to add questions'),)},
        ),
    ]
